# Generated by Django 4.1.7 on 2023-05-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='status',
            field=models.CharField(default='new', max_length=15),
        ),
    ]
